#!/bin/bash
# Automatically generated by FlowForge webhook-test

echo "Triggering n8n local Webhook simulations..."
echo "Base Target URL: http://localhost:5678"

echo "Test 1: Node \"Stripe Webhook\" [POST]"
echo "Endpoint: http://localhost:5678/webhook-test/stripe-events"
curl -X POST -H 'Content-Type: application/json' -d '{
  "id": "evt_1NzABCDEFG12345",
  "object": "event",
  "api_version": "2023-10-16",
  "created": 1699000000,
  "type": "charge.succeeded",
  "data": {
    "object": {
      "id": "ch_1NzABC",
      "amount": 2999,
      "currency": "usd",
      "billing_details": {
        "email": "customer@example.com",
        "name": "Stripe Customer"
      },
      "paid": true,
      "status": "succeeded"
    }
  }
}' "http://localhost:5678/webhook-test/stripe-events"
echo ""
echo "----------------------------------------"

