#!/bin/bash
# Automatically generated by FlowForge webhook-test

echo "Triggering n8n local Webhook simulations..."
echo "Base Target URL: http://localhost:5678"

echo "Test 1: Node \"Shopify Webhook\" [POST]"
echo "Endpoint: http://localhost:5678/webhook-test/shopify-orders"
curl -X POST -H 'Content-Type: application/json' -d '{
  "id": 123456789,
  "email": "buyer@shopify.com",
  "total_price": "150.00",
  "currency": "USD",
  "financial_status": "paid",
  "line_items": [
    {
      "id": 987654321,
      "title": "Developer Tool T-Shirt",
      "quantity": 2,
      "price": "25.00"
    }
  ],
  "customer": {
    "first_name": "John",
    "last_name": "Shopify"
  }
}' "http://localhost:5678/webhook-test/shopify-orders"
echo ""
echo "----------------------------------------"

