#!/bin/bash
# Automatically generated by FlowForge webhook-test

echo "Triggering n8n local Webhook simulations..."
echo "Base Target URL: http://localhost:5678"

echo "Test 1: Node \"DB Webhook trigger\" [POST]"
echo "Endpoint: http://localhost:5678/webhook-test/postgres-insert"
curl -X POST -H 'Content-Type: application/json' -d '{
  "id": "item-100",
  "status": "active",
  "data": {
    "message": "Hello FlowForge",
    "value": 42
  }
}' "http://localhost:5678/webhook-test/postgres-insert"
echo ""
echo "----------------------------------------"

