#!/bin/bash
# Automatically generated by FlowForge webhook-test

echo "Triggering n8n local Webhook simulations..."
echo "Base Target URL: http://localhost:5678"

echo "Test 1: Node \"New Ticket Webhook\" [POST]"
echo "Endpoint: http://localhost:5678/webhook-test/new-ticket"
curl -X POST -H 'Content-Type: application/json' -d '{
  "id": "item-100",
  "status": "active",
  "data": {
    "message": "Hello FlowForge",
    "value": 42
  }
}' "http://localhost:5678/webhook-test/new-ticket"
echo ""
echo "----------------------------------------"

