#!/bin/bash
# Automatically generated by FlowForge webhook-test

echo "Triggering n8n local Webhook simulations..."
echo "Base Target URL: http://localhost:5678"

echo "Test 1: Node \"AI Lead Webhook\" [POST]"
echo "Endpoint: http://localhost:5678/webhook-test/qualify-lead"
curl -X POST -H 'Content-Type: application/json' -d '{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
  "company": "Acme Corp",
  "jobTitle": "Senior Automation Engineer",
  "leadSource": "Web Form"
}' "http://localhost:5678/webhook-test/qualify-lead"
echo ""
echo "----------------------------------------"

