import { N8nWorkflow } from './workflowSchema.js';
import * as fs from 'fs';
import * as path from 'path';

export interface WebhookTestInfo {
  nodeName: string;
  path: string;
  method: string;
  curlCommand: string;
  testUrl: string;
  prodUrl: string;
}

function getStringParam(parameters: Record<string, unknown> | undefined, key: string): string | undefined {
  const value = parameters?.[key];
  return typeof value === 'string' ? value : undefined;
}

export function generateWebhookTest(
  workflow: N8nWorkflow,
  baseUrl: string = 'http://localhost:5678',
  payloadFilePath?: string
): { tests: WebhookTestInfo[]; shScriptContent: string; readmeContent: string } {
  const tests: WebhookTestInfo[] = [];

  const nodes = workflow.nodes || [];
  const webhooks = nodes.filter((n) => n.type === 'n8n-nodes-base.webhook');

  // Set default body payload string if payloadFilePath exists
  let curlBodyArg = '';
  let payloadSummary = 'No request body payload specified.';
  if (payloadFilePath) {
    try {
      const payloadContent = fs.readFileSync(payloadFilePath, 'utf-8');
      curlBodyArg = ` -d '${payloadContent.replace(/'/g, "'\\''")}'`;
      payloadSummary = `Including request body from: \`${path.basename(payloadFilePath)}\``;
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`Could not read payload file: ${message}. Generating command without body.`);
    }
  }

  for (const node of webhooks) {
    const webhookPath = getStringParam(node.parameters, 'path') || 'webhook-trigger-path';
    const method = (getStringParam(node.parameters, 'httpMethod') || 'POST').toUpperCase();
    const cleanBaseUrl = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl;

    // n8n structures paths:
    // Test Url: /webhook-test/<path>
    // Production Url: /webhook/<path>
    const testUrl = `${cleanBaseUrl}/webhook-test/${webhookPath}`;
    const prodUrl = `${cleanBaseUrl}/webhook/${webhookPath}`;

    const headers = method !== 'GET' ? " -H 'Content-Type: application/json'" : '';
    const curlCommand = `curl -X ${method}${headers}${curlBodyArg} "${testUrl}"`;

    tests.push({
      nodeName: node.name,
      path: webhookPath,
      method,
      curlCommand,
      testUrl,
      prodUrl
    });
  }

  // Generate Shell Script
  let shScriptContent = '#!/bin/bash\n# Automatically generated by FlowForge webhook-test\n\n';
  shScriptContent += `echo "Triggering n8n local Webhook simulations..."\n`;
  shScriptContent += `echo "Base Target URL: ${baseUrl}"\n\n`;

  tests.forEach((t, i) => {
    shScriptContent += `echo "Test ${i + 1}: Node \\"${t.nodeName}\\" [${t.method}]"\n`;
    shScriptContent += `echo "Endpoint: ${t.testUrl}"\n`;
    shScriptContent += `${t.curlCommand}\n`;
    shScriptContent += 'echo ""\n';
    shScriptContent += 'echo "----------------------------------------"\n\n';
  });

  // Generate README Content
  let readmeContent = `# Local Webhook Testing Instructions

This guide assists in executing local webhook trigger runs for your workflow.

**Configuration:**
*   **Base URL Target:** \`${baseUrl}\`
*   **Payload state:** ${payloadSummary}

## Targets Found

`;

  tests.forEach((t, i) => {
    readmeContent += `### Webhook ${i + 1}: ${t.nodeName}
*   **Method:** \`${t.method}\`
*   **Active webhook path:** \`${t.path}\`
*   **n8n Webhook URLs:**
    *   **Test URL (for visual editor active debugging):** \`${t.testUrl}\`
    *   **Production URL (for activated workflow executions):** \`${t.prodUrl}\`

#### Test Execution Curl:
\`\`\`bash
${t.curlCommand}
\`\`\`

`;
  });

  readmeContent += `
## Important Note on n8n Webhook Node Behavior
n8n distinguishes between **Test URLs** and **Production URLs**:
1.  **Test URLs:** Only listen when you actively click the **"Listen for test event"** button inside the n8n UI editor canvas. If you invoke this curl when not listening, n8n will return a \`404 Webhook not found\` error.
2.  **Production URLs:** Require the workflow to be marked **"Active"** (toggled on). Once enabled, it listens continuously, running in the background.
`;

  return { tests, shScriptContent, readmeContent };
}
